# Welcome to Chat Overhaul
# This is a simple plugin that will overhaul your chat.

# This is what the plugin prefix will be, i.e.: "[Chat Overhaul] plugin reloaded"
plugin-prefix: "&e[&cChat Overhaul&e] "

staffchat:
  # This enables/disables the staffchat feature
  enable-sc: true

  # This is the trigger for staffchat
  # for the default "# " to use staffchat you type
  # '# this is staff chat' to use staffchat
  staffchat-trigger: "# "

  # This controls the staffchat format
  # <player> - player name
  # <message> - player message
  staffchat-format: "&7[&eStaffChat&7]&e <player>&7 >>&e <message>"

# Announcement settings
announce:
  # This enables/disables the /announcement command
  enable-announce: true

  # This determines weather the announcement should
  # have a sound or not
  play-sound: false

  # This is where you can customize the format for the announcement.
  # <message> - player message
  announce-format: "&c[&eBroadcast&c] <message>"

# This section is the entire config for groups, aside for setting the group visual itself
# you can find that in the groups.yml file.
groups:
  # This enables/disables groups. (defaults to false)
  enable-groups: false

  # These are the names of the groups
  # NOTE: these have to be THE SAME as the ones in groups.yml
  # For a player to be part of a group, they need the permission:
  # chat.group.<group name>
  # Example for 'admin': chat.group.admin
  # NOTE: The order it searches for is from top to bottom, in this example,
  # It will see if the player is in the admin group, THEN the mod group.
  group-names: ["admin", "mod"]

# This is what will show when a player sends a message (default)
# Vanilla default: "&f<<player>> <message>"
# <player> - player name
# <message> - player message
message-format: "&f<player>&7 >>&f <message>"

# Enable or disable Join/Leave messages
enable-join: true
enable-leave: true

# This will set the join/leave message
join-format: "&7[&a+&7] <player>"
leave-format: "&7[&c-&7] <player>"

# This is the format of the /msg command for both the receiver and sender
# <sender> - user that used the /msg command
# <player> - player that receives the message
# <message> - the message
message-command-format-receiver: "&7[&e<sender>&7 ->&e You&7] <message>"
message-command-format-sender: "&7[&eYou&7 ->&e <player>&7] <message>"
