name: SimpleChatOverhaul
version: 1.2.4
main: me.mystc.simplechatoverhaul.SimpleChatOverhaul
api-version: 1.18
authors: [mystc]
description: A simple plugin that overhauls the chat.
commands:
  coreload:
    description: Reloads the plugin
    aliases: [chatreload, chatoverhaulreload]
  message:
    description: message a player on the server
    aliases: [msg, whisper, w, tell]
  reply:
    description: reply to the last player you messaged
    aliases: [r]
  announce:
    description: sends a message to all players as an announcement/broadcast
    aliases: [anc, announcement, broadcast, bc, brc, brdc]
  staffchat:
    description: toggle staff chat
    aliases: [staffchattoggle, sct, sc]
permissions:
  chat.reload:
    description: Allows you to use the reload command
    default: op
  chat.message:
    description: Allows you to use the message command
    default: true
  chat.reply:
    description: Allows you to use the reply command
    default: true
  chat.announce:
    description: Allows you to use the announce command
    default: op
  chat.staff:
    description: Allows you to use staffchat
    default: op
